# Sprint 4 - Software Tools Project

For the stremlit app I decided to make a basic overview of the odometer reading data. We will see how odometer reading compare to other data through scatter plots, histograms of what the most frequent odometer readings were, and bar charts looking at the average odometer readings for certain car types/colors etc.

In [54]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import plotly.express as px

Lets clean up and enhance the data first

In [12]:
df_vehicles = pd.read_csv("../vehicles_us.csv")
display(df_vehicles.sample(10))
df_vehicles.info()

price  model_year                       model  condition  cylinders  \
27468   3200      1998.0                  ford f-150       good        6.0   
46261  14988      2010.0               toyota tundra  excellent        8.0   
1102   10000      2011.0              subaru outback  excellent        4.0   
4503   14999         NaN  chevrolet silverado 2500hd  excellent        8.0   
45313   2599      2014.0                  honda cr-v   like new        4.0   
2380    2500      2005.0                 ford escape       fair        4.0   
15514  21999      2018.0                ford mustang   like new        4.0   
35902  22000      2008.0               toyota tundra  excellent        8.0   
12729  21000      2013.0                    ram 1500  excellent        8.0   
27291  19900      2015.0               jeep wrangler   like new        6.0   

      fuel  odometer transmission    type paint_color  is_4wd date_posted  \
27468  gas  175000.0    automatic   truck       brown     NaN  2018-10-12   
46261  gas  190000.0    automatic   truck      silver     1.0  2018-05-17   
1102   gas  140000.0       manual   wagon        grey     1.0  2019-02-23   
4503   gas  104344.0    automatic  pickup       white     1.0  2019-01-12   
45313  gas   37539.0    automatic     SUV        grey     1.0  2018-12-21   
2380   gas       NaN    automatic     SUV       white     NaN  2019-01-08   
15514  gas   31000.0    automatic   coupe       white     NaN  2018-08-17   
35902  gas       NaN    automatic   truck        grey     1.0  2018-08-27   
12729  gas  104000.0    automatic   truck       brown     1.0  2018-12-22   
27291  gas   77000.0        other     SUV       white     1.0  2018-06-14   

       days_listed  
27468           23  
46261           54  
1102             5  
4503            29  
45313           88  
2380            80  
15514           12  
35902           58  
12729           21  
27291           17

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   price         51525 non-null  int64  
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  object 
 3   condition     51525 non-null  object 
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  object 
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  object 
 8   type          51525 non-null  object 
 9   paint_color   42258 non-null  object 
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  object 
 12  days_listed   51525 non-null  int64  
dtypes: float64(4), int64(2), object(7)
memory usage: 5.1+ MB


Cleaning up the data by by replacing missing values in is_4wd to 0 since its a true false column

In [13]:
df_vehicles['is_4wd'].unique()

array([ 1., nan])

In [20]:
df_vehicles['is_4wd'].fillna(0,inplace=True)
df_vehicles['is_4wd'] = df_vehicles['is_4wd'].astype("int")
df_vehicles['is_4wd'].unique()

array([1, 0])

Checking for duplicates:

In [49]:
df_vehicles.duplicated().sum()

0

Seeing how the model column is made up so I can make a "make" column for easier EDA

In [39]:
sorted(df_vehicles['model'].unique())

['acura tl',
 'bmw x5',
 'buick enclave',
 'cadillac escalade',
 'chevrolet camaro',
 'chevrolet camaro lt coupe 2d',
 'chevrolet colorado',
 'chevrolet corvette',
 'chevrolet cruze',
 'chevrolet equinox',
 'chevrolet impala',
 'chevrolet malibu',
 'chevrolet silverado',
 'chevrolet silverado 1500',
 'chevrolet silverado 1500 crew',
 'chevrolet silverado 2500hd',
 'chevrolet silverado 3500hd',
 'chevrolet suburban',
 'chevrolet tahoe',
 'chevrolet trailblazer',
 'chevrolet traverse',
 'chrysler 200',
 'chrysler 300',
 'chrysler town & country',
 'dodge charger',
 'dodge dakota',
 'dodge grand caravan',
 'ford econoline',
 'ford edge',
 'ford escape',
 'ford expedition',
 'ford explorer',
 'ford f-150',
 'ford f-250',
 'ford f-250 sd',
 'ford f-250 super duty',
 'ford f-350 sd',
 'ford f150',
 'ford f150 supercrew cab xlt',
 'ford f250',
 'ford f250 super duty',
 'ford f350',
 'ford f350 super duty',
 'ford focus',
 'ford focus se',
 'ford fusion',
 'ford fusion se',
 'ford mustang',
 '

Making a "make" column using the first work in the "model" column:

In [42]:
df_vehicles['make'] = df_vehicles['model'].str.split().str[0]
cols = df_vehicles.columns.tolist() 
cols.insert(2, cols.pop(cols.index('make')))
df_vehicles = df_vehicles[cols]
df_vehicles.head(5)

price  model_year      make           model  condition  cylinders fuel  \
0   9400      2011.0       bmw          bmw x5       good        6.0  gas   
1  25500         NaN      ford      ford f-150       good        6.0  gas   
2   5500      2013.0   hyundai  hyundai sonata   like new        4.0  gas   
3   1500      2003.0      ford      ford f-150       fair        8.0  gas   
4  14900      2017.0  chrysler    chrysler 200  excellent        4.0  gas   

   odometer transmission    type paint_color  is_4wd date_posted  days_listed  
0  145000.0    automatic     SUV         NaN       1  2018-06-23           19  
1   88705.0    automatic  pickup       white       1  2018-10-19           50  
2  110000.0    automatic   sedan         red       0  2019-02-07           79  
3       NaN    automatic  pickup         NaN       0  2019-03-22            9  
4   80903.0    automatic   sedan       black       0  2019-04-02           28

I noticed something odd about mercedes cars that it looks like none of the entries have odometer readings

In [159]:
df_vehicles.query('make == "mercedes-benz"')['odometer'].unique()

array([nan])

Indeed they do not, since my simple analysis will focus on odometer readings I will remove these from my dataframe

In [164]:
df_vehicles.query('make != "mercedes-benz"',inplace=True)
df_vehicles['make'].unique()

array(['bmw', 'ford', 'hyundai', 'chrysler', 'toyota', 'honda', 'kia',
       'chevrolet', 'ram', 'gmc', 'jeep', 'nissan', 'subaru', 'dodge',
       'acura', 'cadillac', 'volkswagen', 'buick'], dtype=object)

Data is cleaned and enhances so we can begin doing some basic analysis on the data focusing on the odometer readings

Scatter plot example to compare price odometerreadings to see how they correlate in a specific car. The idea being that the values of the car can easily be changed to different makes and models on the app using streamlit.

In [157]:
make = "acura"
model = "toyota camry"
one_vehicle = df_vehicles.query(f"make == '{make}'")
one_make = df_vehicles.query(f"model == '{model}'")
y_val="price"
x_val="odometer"
fig=px.scatter(
    one_vehicle,
    title=f'price vs odometer reading of {make} cars',
    #title=f'price vs odometer reading of {model} cars',
    y='price',
    x='odometer'
)
fig.update_layout(xaxis_title='odometer reading',yaxis_title='price ($ USD)')
fig

Plotting a histogram of the odometer readings in the car vs other values such as the condition. the comparison can be changed to other categorical values in the data on the streamline app

In [148]:
comparison='condition'
fig=px.histogram(
        df_vehicles,
        title=f'Histogram of odometer reading frequency per vehicle {comparison}',
        x='odometer',
        color=f'{comparison}',
        nbins=100
    )
fig.update_layout(xaxis_title='Odometer Reading',yaxis_title='Frequency')
fig

Finally making a bar chart to compare the average odometer reading of the vehicles for specific categories of the vehicle. Again the idea being these categories can be changed dynamically on the app using streamlit.

In [146]:
comparison_2 = 'paint_color'
df_od_by_color = df_vehicles.groupby(f'{comparison_2}')['odometer'].mean()
fig=px.bar(
    df_od_by_color,
    title=f'Average odometer reading per vehicle {comparison_2}'
)
fig.update_layout(showlegend=False, yaxis_title='Average Odometer Reading')
fig